{
 "title": "localdash",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:10.000Z" },
 "templating": {
  "list": [
   {
    "name": "run",
    "query": "select distinct try::text ||'-'||try::text  from send  "
   },
   { "name": "type", "query": "pps,bps" },
   { "name": "protocol", "query": "tcp,udp" },
   { "name": "strt", "query": "0,125" },
   { "name": "stp", "query": "875,999,1000" },
   { "name": "CI", "query": "0.99, 0.95" }
  ]
 },
 "panels": [
  {
   "title": "Overall ${type} By Run",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select cast(try as text) as try  , \n      avg(aes_sender_tp) aes_sender_tp, \n      avg(plain_sender_tp) plain_sender_tp, \n      avg(aes_receiver_tp) aes_receiver_tp, \n      avg(plain_receiver_tp) plain_receiver_tp \nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_sender_tp,\n    sum(case when is_sender = 0 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_receiver_tp  \nfrom(\n\n  select is_aes,\n      is_sender, \n      try,\n  \t\tstp , \n  \t\tcount(*) cnt, \n  \t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n  \t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n  \t\tsum(rt) rt,\n  \t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate \n  from send \n  where try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\n  group by is_aes,is_sender,try, stp \n  order by is_aes,is_sender, try, stp ) a\n  group by stp,try\n) q\ngroup by try;"
    }
   ]
  },
  {
   "title": "Overall  ${type} Difference By Run",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select cast(try as text) as try  , \n      avg(aes_sender_tp) - avg(plain_sender_tp) sender_difference_tp, \n      avg(aes_receiver_tp) - avg(plain_receiver_tp) receiver_difference_tp--,\n      --avg(bitrate) bitrate\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_receiver_tp, \n    avg(bitrate) bitrate\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate,\n\t\tavg(bitrate) bitrate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try;"
    }
   ]
  },
  {
   "title": "Overall  Difference Percent By Run",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select  cast(try as text) as t   , \n        (sum(aes_sender_tp) - sum(plain_sender_tp))/sum(plain_sender_tp) sender_difference_percent_tp, \n        (sum(aes_receiver_tp) - sum(plain_receiver_tp))/sum(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp\norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try;"
    }
   ]
  },
  {
   "title": "Total ${type}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select 0 as time  , sum(aes_sender_t) aes_sender_t, sum(plain_sender_t) plain_sender_t, sum(aes_receiver_t) aes_receiver_t, sum(plain_receiver_t) plain_receiver_t\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t t  else 0 end) plain_sender_t,\n    sum(case when is_sender = 0 and is_aes = 1 then t  else 0 end) aes_receiver_t ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t t  else 0 end) plain_receiver_t \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end)/(case when '${type}'= 'bps' then 1 else 1310 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q ;"
    }
   ]
  },
  {
   "title": "Overall  ${type} Average",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "select 0 as time , \n      avg(aes_sender_tp) aes_sender_tp, \n      avg(plain_sender_tp) plain_sender_tp, \n      avg(aes_receiver_tp) aes_receiver_tp, \n      avg(plain_receiver_tp) plain_receiver_tp\nfrom(\nselect try as time  , \n       avg(aes_sender_tp) aes_sender_tp, \n       avg(plain_sender_tp) plain_sender_tp, \n       avg(aes_receiver_tp) aes_receiver_tp, \n       avg(plain_receiver_tp) plain_receiver_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp  else 0 end) plain_sender_tp,\n    sum(case when is_sender = 0 and is_aes = 1 then tp  else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp  else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end)/(case when '${type}'= 'bps' then 1 else 1310 end) tp\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try)r;"
    }
   ]
  },
  {
   "title": "Overall ${type} Avg. Diff",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select 0 as time , avg(sender_difference_tp) sender_difference_tp, avg(receiver_difference_tp) receiver_difference_tp\nfrom (\nselect try as time  , avg(aes_sender_tp) - avg(plain_sender_tp) sender_difference_tp, avg(aes_receiver_tp) - avg(plain_receiver_tp) receiver_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp\nhaving try  in ( ${run} )\norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try) r;"
    }
   ]
  },
  {
   "title": "Overall  ${type} Average Diff%",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select 0 as time , avg(sender_difference_percent_tp) sender_difference_percent_tp, avg(receiver_percent_difference_tp) receiver_percent_difference_tp\nfrom(\nselect try as time  , (avg(aes_sender_tp) - avg(plain_sender_tp))/avg(plain_sender_tp) sender_difference_percent_tp, (avg(aes_receiver_tp) - avg(plain_receiver_tp))/avg(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp/(case when '${type}'= 'bps' then 1 else 1310 end) else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try)r;"
    }
   ]
  },
  {
   "title": "Total Retransmission Difference By Run",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "\nselect cast(try as text) as try  , \n        sum(aes_sender_rt)/sum(aes_sender_t) aes_sender_rt, \n        sum(plain_sender_rt)/sum(plain_sender_t) plain_sender_rt\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then rt else 0 end) aes_sender_rt ,\n    sum(case when is_sender = 1 and is_aes = 0 then rt else 0 end) plain_sender_rt,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then t else 0 end) plain_sender_t\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(rt*1310) rt,\n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try;"
    }
   ]
  },
  {
   "title": "Total Retransmission  Percent By Run",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select cast(try as text) as try  ,  \n        sum(aes_sender_rt)/sum(aes_sender_t-aes_sender_rt) aes_sender_rt, \n        sum(plain_sender_rt)/sum(plain_sender_t-plain_sender_rt) plain_sender_rt\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then rt else 0 end) aes_sender_rt ,\n    sum(case when is_sender = 1 and is_aes = 0 then rt else 0 end) plain_sender_rt,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then t else 0 end) plain_sender_t\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(rt*1310) rt,\n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try;"
    }
   ]
  },
  {
   "title": "Total Retransmission Diff",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "select 0 as time  , (sum(plain_sender_rt)-sum(aes_sender_rt)) aes\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then rt else 0 end) aes_sender_rt ,\n    sum(case when is_sender = 1 and is_aes = 0 then rt else 0 end) plain_sender_rt,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then t else 0 end) plain_sender_t\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(rt*1310) rt,\n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q ;"
    }
   ]
  },
  {
   "title": "Total Retransmission Percent Difference",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select 0 as time  , (aes_sender-plain_sender)/plain_sender aes\nfrom (\nselect 0 as time  , sum(aes_sender_rt)/sum(aes_sender_t) aes_sender, sum(plain_sender_rt)/sum(plain_sender_t) plain_sender\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then rt else 0 end) aes_sender_rt ,\n    sum(case when is_sender = 1 and is_aes = 0 then rt else 0 end) plain_sender_rt,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then t else 0 end) plain_sender_t\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(rt*1310) rt,\n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q )s;"
    }
   ]
  },
  {
   "title": "Total Retransmission  Percent",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select 0 as time  , sum(aes_sender_rt)/sum(aes_sender_t-aes_sender_rt) aes_sender_rt, sum(plain_sender_rt)/sum(plain_sender_t-plain_sender_rt) plain_sender_rt\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then rt else 0 end) aes_sender_rt ,\n    sum(case when is_sender = 1 and is_aes = 0 then rt else 0 end) plain_sender_rt,\n    sum(case when is_sender = 1 and is_aes = 1 then t else 0 end) aes_sender_t ,\n    sum(case when is_sender = 1 and is_aes = 0 then t else 0 end) plain_sender_t\nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tsum(rt*1310) rt,\n\t\tsum(case when t_type = 'MBytes' then t*1000000 else t*1000 end) t\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q ;"
    }
   ]
  },
  {
   "title": "Overall  Sender Difference Percent By Run with CI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--Confidence interval = mean ± CI(stddev ÷ SQRT(n))\n\nwith   b as (\n    \n\nselect (try-1)*1000 as time  , \n        (sum(aes_sender_tp) - sum(plain_sender_tp))/sum(plain_sender_tp) sender_difference_percent_tp, \n        (sum(aes_receiver_tp) - sum(plain_receiver_tp))/sum(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try\n\n), \n    probs as( SELECT \n                AVG(sender_difference_percent_tp)           as mean,\n                COUNT(*)           as cnt,\n                1.0*SUM(case when sender_difference_percent_tp>0 then 1 else 0 end)/COUNT(*) as proportion,\n                stddev(sender_difference_percent_tp)         as stddev,\n                stddev(sender_difference_percent_tp)/count(*) stderr,\n                stddev(sender_difference_percent_tp)/count(*)/2 marginoferror\nFROM b )\n\n\n\nselect time , \n        sender_difference_percent_tp, \n        sender_difference_percent_tp sender_difference_percent_tp_fill, \n        sender_difference_percent_tp   +${CI}*( probs.stddev / SQRT(probs.cnt)) up, \n         sender_difference_percent_tp -  ${CI}*( probs.stddev / SQRT(probs.cnt)) down,\n         mean +   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_up, \n         mean -   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_down\nfrom probs,  b\norder by time;\n\n"
    }
   ]
  },
  {
   "title": "Overall  Receiver Difference Percent By Run with CI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--Confidence interval = mean ± CI(stddev ÷ SQRT(n))\n\nwith   b as (\n    \n\nselect (try-1)*1000 as time  , \n        (sum(aes_sender_tp) - sum(plain_sender_tp))/sum(plain_sender_tp) sender_difference_percent_tp, \n        (sum(aes_receiver_tp) - sum(plain_receiver_tp))/sum(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by try\n\n), \n    probs as( SELECT \n                AVG(receiver_percent_difference_tp)           as mean,\n                COUNT(*)           as cnt,\n                1.0*SUM(case when receiver_percent_difference_tp>0 then 1 else 0 end)/COUNT(*) as proportion,\n                stddev(receiver_percent_difference_tp)         as stddev,\n                stddev(receiver_percent_difference_tp)/count(*) stderr,\n                stddev(receiver_percent_difference_tp)/count(*)/2 marginoferror\nFROM b )\n\n\n\nselect time , \n        receiver_percent_difference_tp, \n        receiver_percent_difference_tp receiver_percent_difference_tp_fill, \n        receiver_percent_difference_tp   +${CI}*( probs.stddev / SQRT(probs.cnt)) up, \n         receiver_percent_difference_tp -  ${CI}*( probs.stddev / SQRT(probs.cnt)) down,\n         mean +   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_up, \n         mean -   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_down\nfrom probs,  b\norder by time;\n\n"
    }
   ]
  },
  {
   "title": "Total  Sender By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp ,  \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try\norder by time;"
    }
   ]
  },
  {
   "title": "Total  Receiver By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp ,  \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send \nwhere  try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try;"
    }
   ]
  },
  {
   "title": "Total  Sender Difference By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select time, (aes_sender_tp - plain_sender_tp) as sender_tp_difference --try,stp,\nfrom(\nselect stp+(1000 * (try-1))  as time,--,try,stp,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp ,  \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send \nwhere  try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) r\nwhere aes_sender_tp > 0 and plain_sender_tp > 0;"
    }
   ]
  },
  {
   "title": "Total  Sender Difference Percent By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select time, ((aes_sender_tp - plain_sender_tp)/plain_sender_tp) as sender_tp_difference_percent --try,stp,\nfrom(\nselect stp+(1000 * (try-1))  as time,--,try,stp,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp ,  \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send  \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) r\nwhere aes_sender_tp > 0 and plain_sender_tp > 0;"
    }
   ]
  },
  {
   "title": "Total  Receiver Difference By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select time, (aes_receiver_tp - plain_receiver_tp) as receiver_tp_difference --try,stp,\nfrom(\nselect stp+(1000 * (try-1))  as time,--,try,stp,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send \nwhere  try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) r\nwhere aes_receiver_tp > 0 and plain_receiver_tp > 0;"
    }
   ]
  },
  {
   "title": "Total  Receiver Difference Percent By Run&Step",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select time, ((aes_sender_tp - plain_sender_tp)/plain_sender_tp) as sender_tp_difference_percent --try,stp,\nfrom(\nselect stp+(1000 * (try-1))  as time,--,try,stp,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp ,  \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \nfrom send \nwhere  try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) r\nwhere aes_sender_tp > 0 and plain_sender_tp>0;"
    }
   ]
  },
  {
   "title": "Difference Percent By Run with CI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--Confidence interval = mean ± CI(stddev ÷ SQRT(n))\n\nwith   b as (\n    \n\nselect  time  , (sum(aes_sender_tp) - sum(plain_sender_tp))/sum(plain_sender_tp) sender_difference_percent_tp, (sum(aes_receiver_tp) - sum(plain_receiver_tp))/sum(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by time\n\n), \n    probs as( SELECT \n                AVG(sender_difference_percent_tp)           as mean,\n                COUNT(*)           as cnt,\n                1.0*SUM(case when sender_difference_percent_tp>0 then 1 else 0 end)/COUNT(*) as proportion,\n                stddev(sender_difference_percent_tp)         as stddev,\n                stddev(sender_difference_percent_tp)/count(*) stderr,\n                stddev(sender_difference_percent_tp)/count(*)/2 marginoferror\nFROM b )\n\n\n\nselect time , sender_difference_percent_tp, \n        sender_difference_percent_tp   +${CI}*( probs.stddev / SQRT(probs.cnt)) up, \n         sender_difference_percent_tp -  ${CI}*( probs.stddev / SQRT(probs.cnt)) down,\n         mean +   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_up, \n         mean -   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_down\nfrom probs,  b\norder by time;\n\n"
    }
   ]
  },
  {
   "title": "Total  Receiver Difference Percent By Run&Step with CI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--Confidence interval = mean ± CI(stddev ÷ SQRT(n))\n\nwith   b as (\n    select time, ((aes_sender_tp - plain_sender_tp)/plain_sender_tp) as sender_tp_difference_percent  \n    from(\n    select stp+(1000 * (try-1))  as time,--,try,stp,\n        sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n        sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp \n    from(\n\n    select is_aes,\n        is_sender, \n        try,\n            stp ,  \n            sum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp \n    from send \n    where  try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\n    group by is_aes,is_sender,try, stp \n    order by is_aes,is_sender, try, stp ) a\n    group by stp,try) r\n    where aes_sender_tp > 0 and plain_sender_tp>0\n\n), \n    probs as( SELECT \n                AVG(sender_tp_difference_percent)           as mean,\n                COUNT(*)           as cnt,\n                1.0*SUM(case when sender_tp_difference_percent>0 then 1 else 0 end)/COUNT(*) as proportion,\n                stddev(sender_tp_difference_percent)         as stddev,\n                stddev(sender_tp_difference_percent)/count(*) stderr,\n                stddev(sender_tp_difference_percent)/count(*)/2 marginoferror\nFROM b )\n\n\n\nselect time , sender_tp_difference_percent, \n        sender_tp_difference_percent  + ${CI}*( probs.stddev / SQRT(probs.cnt)) up, \n         sender_tp_difference_percent  - ${CI}*( probs.stddev / SQRT(probs.cnt)) down\nfrom probs,  b;"
    }
   ]
  },
  {
   "title": "Difference Percent By Run with CI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--Confidence interval = mean ± CI(stddev ÷ SQRT(n))\n\nwith   b as (\n    \n\nselect  time  , (sum(aes_sender_tp) - sum(plain_sender_tp))/sum(plain_sender_tp) sender_difference_percent_tp, (sum(aes_receiver_tp) - sum(plain_receiver_tp))/sum(plain_receiver_tp) receiver_percent_difference_tp\nfrom \n(\nselect try,stp+(1000 * (try-1))  as time,\n    sum(case when is_sender = 1 and is_aes = 1 then tp else 0 end) aes_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 1 then tp else 0 end) aes_receiver_tp ,\n    sum(case when is_sender = 1 and is_aes = 0 then \t tp else 0 end) plain_sender_tp ,\n    sum(case when is_sender = 0 and is_aes = 0 then \t tp else 0 end) plain_receiver_tp \nfrom(\n\nselect is_aes,\n    is_sender, \n    try,\n\t\tstp , \n\t\tcount(*) cnt, \n\t\tsum(case when tp_type = 'Gbits/sec' then tp*1000000000 else tp*1000000 end) tp, \n\t\tsum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310 t, \n\t\tsum(rt) rt,\n\t\tsum(rt)/(sum(case when t_type = 'MBytes' then tp*1000000 else t*1000 end)/1310) rt_rate\nfrom send \nwhere try  in ( ${run} ) and strt >= ${strt} and stp <= ${stp}  and (( '${protocol}' = 'tcp' and is_tcp = 1) or ( '${protocol}' = 'udp' and is_tcp = 0) )\ngroup by is_aes,is_sender,try, stp \norder by is_aes,is_sender, try, stp ) a\ngroup by stp,try) q\ngroup by time\n\n), \n    probs as( SELECT \n                AVG(sender_difference_percent_tp)           as mean,\n                COUNT(*)           as cnt,\n                1.0*SUM(case when sender_difference_percent_tp>0 then 1 else 0 end)/COUNT(*) as proportion,\n                stddev(sender_difference_percent_tp)         as stddev,\n                stddev(sender_difference_percent_tp)/count(*) stderr,\n                stddev(sender_difference_percent_tp)/count(*)/2 marginoferror\nFROM b )\n\n\n\nselect time , sender_difference_percent_tp, \n        sender_difference_percent_tp   +${CI}*( probs.stddev / SQRT(probs.cnt)) up, \n         sender_difference_percent_tp -  ${CI}*( probs.stddev / SQRT(probs.cnt)) down,\n         mean +   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_up, \n         mean -   ${CI}*( probs.stddev / SQRT(probs.cnt)) CI_down\nfrom probs,  b\norder by time;\n\n"
    }
   ]
  }
 ]
}